import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from 'src/styles/Home.module.css';
import { HouseCards } from 'src/components/houseCards/HouseCards';
import {
  getRunningQueriesThunk,
  housesApi,
  HousesResponse,
} from 'src/redux/api/housesApi';
import { wrapper } from 'src/redux';
import { GetServerSideProps } from 'next';
import { Pagination } from 'src/components/pagination/Pagination';
import { TestErrorBoundary } from 'src/components/testErrorBoundary/TestErrorBoundary';
import { ParsedData, parseLinkHeader } from 'src/utils/parseLinkHeader';

const inter = Inter({ subsets: ['latin'] });

interface HomeProps {
  data: HousesResponse;
  parsedLink: ParsedData | undefined;
}

export default function Home(props: HomeProps) {
  console.log(props.parsedLink);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <TestErrorBoundary />
        <Pagination parsedLink={props.parsedLink} />
        <div className={styles.cardsContainer}>
          <HouseCards data={props.data} />
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (ctx) => {
    store.dispatch(
      housesApi.endpoints.getHouses.initiate('page=1&pageSize=10&region=dorne')
    );
    const result = await Promise.all(store.dispatch(getRunningQueriesThunk()));
    const data = result[0].data as HousesResponse;
    // const parsedLink = parseLinkHeader(data.parsedLink as string);
    const parsedLink = data.parsedLink as string;

    return { props: { data, parsedLink } };
  });
