import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { HouseCards } from 'src/components/houseCards/HouseCards';
import {
  getRunningQueriesThunk,
  housesApi,
  HousesResponse,
} from 'src/redux/api/housesApi';
import { wrapper } from 'src/redux';
import { GetServerSideProps } from 'next';
import { TestErrorBoundary } from 'src/components/testErrorBoundary/TestErrorBoundary';
import { ParsedData } from 'src/utils/parseLinkHeader';

interface HomeProps {
  data: HousesResponse;
  parsedLink: ParsedData;
}

export default function Home(props: HomeProps) {
  return (
    <>
      <Head>
        <title>SergioAJS-RS-School-ReactQ4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <TestErrorBoundary />
        <div className={styles.cardsContainer}>
          <HouseCards data={props.data} />
        </div>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async () => {
    store.dispatch(
      housesApi.endpoints.getHouses.initiate('page=1&pageSize=10&region=dorne')
    );
    const result = await Promise.all(store.dispatch(getRunningQueriesThunk()));
    const data = result[0].data as HousesResponse;

    return { props: { data } };
  });
